-- Generated from template

require('util')
--require('physics')
require('multiteam')
require('stat_tracker')
require('cott')

--[[if ReflexGameMode == nil then
    print ( '[REFLEX] creating reflex game mode' )
	  ReflexGameMode = class({})
end]]

function Precache( context )
	--[[
		Precache things we know we'll use.  Possible file types include (but not limited to):
			PrecacheResource( "model", "*.vmdl", context )
			PrecacheResource( "soundfile", "*.vsndevts", context )
			PrecacheResource( "particle", "*.vpcf", context )
			PrecacheResource( "particle_folder", "particles/folder", context )
	]]
		PrecacheUnitByNameSync('npc_dota_hero_axe', context)
    	PrecacheResource("soundfile", "*.vsndevts", context)
        PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_tiny.vsndevts", context)
        PrecacheResource("soundfile", "soundevents/game_sounds_heroes/game_sounds_stormspirit.vsndevts", context)
    	PrecacheResource("particle", "particles/msg_fx/msg_xp.vpcf", context)
    	PrecacheResource("particle", "particles/units/heroes/hero_slark/slark_essence_shift_hit_spill_streak.vpcf", context)
    	PrecacheResource("particle", "particles/world_environmental_fx/bluelamp_flame_torch.vpcf", context)
    	PrecacheResource("particle", "particles/units/heroes/hero_witchdoctor/witchdoctor_voodoo_restoration_heal.vpcf", context)
    	PrecacheResource("particle", "particles/units/heroes/hero_witchdoctor/witchdoctor_voodoo_restoration_heal_radiant.vpcf", context)
        PrecacheResource("particle", "particles/units/heroes/hero_tiny/tiny_transform.vpcf", context)
        PrecacheResource("particle", "particles/units/heroes/hero_tiny/tiny_transform_b.vpcf", context)
        PrecacheResource("particle", "particles/units/heroes/hero_tiny/tiny_transform_c.vpcf", context)
        PrecacheResource("particle", "particles/units/heroes/hero_tiny/tiny_transform_d.vpcf", context)
        PrecacheResource("particle", "particles/units/heroes/hero_obsidian_destroyer/obsidian_death_cloud.vpcf", context)
        PrecacheResource("particle", "particles/units/heroes/hero_leshrac/leshrac_lightning_slow.vpcf", context)
        PrecacheResource("particle", "particles/units/heroes/hero_puck/puck_phase_shift.vpcf", context)
        PrecacheResource("particle", "particles/units/heroes/hero_puck/puck_phase_shift_b.vpcf", context)
        PrecacheResource("particle", "particles/units/heroes/hero_puck/puck_phase_shift_c.vpcf", context)
    	PrecacheModel("models/props_debris/clay_pots_broken001a.vmdl", context)
    	PrecacheModel("models/items/juggernaut/ward/healing_gills_of_the_lost_isles/healing_gills_of_the_lost_isles.vmdl", context)
    	PrecacheModel("models/heroes/pedestal/pedestal_1_small.vmdl", context)
    	PrecacheModel("models/lina_statue/lina_statue_000001.vmdl", context)
    	PrecacheModel("models/lina_statue/lina_statue_000002.vmdl", context)
    	PrecacheModel("models/lina_statue/lina_statue_000003.vmdl", context)
    	PrecacheModel("models/lina_statue/lina_statue_000004.vmdl", context)
    	PrecacheModel("models/lina_statue/lina_statue_000005.vmdl", context)
    	PrecacheModel("models/lina_statue/lina_statue_000006.vmdl", context)
    	PrecacheModel("models/lina_statue/lina_statue_000007.vmdl", context)
    	PrecacheModel("models/lina_statue/lina_statue_000008.vmdl", context)
    	PrecacheModel("models/lina_statue/lina_statue_000009.vmdl", context)
    	PrecacheModel("models/lina_statue/lina_statue_000010.vmdl", context)
        PrecacheModel("models/lina_statue/lina_statue_000011.vmdl", context)
        PrecacheModel("models/qop_statue/qop_statue_000001.vmdl", context)
        PrecacheModel("models/qop_statue/qop_statue_000002.vmdl", context)
        PrecacheModel("models/qop_statue/qop_statue_000003.vmdl", context)
        PrecacheModel("models/qop_statue/qop_statue_000004.vmdl", context)
        PrecacheModel("models/qop_statue/qop_statue_000005.vmdl", context)
        PrecacheModel("models/qop_statue/qop_statue_000006.vmdl", context)
        PrecacheModel("models/qop_statue/qop_statue_000007.vmdl", context)
        PrecacheModel("models/qop_statue/qop_statue_000008.vmdl", context)
        PrecacheModel("models/qop_statue/qop_statue_000009.vmdl", context)
        PrecacheModel("models/qop_statue/qop_statue_000010.vmdl", context)
        PrecacheModel("models/qop_statue/qop_statue_000011.vmdl", context)
        PrecacheModel("models/heroes/tiny_01/tiny_01.vmdl", context)
		PrecacheUnitByNameSync('npc_precache_everything', context)
end

-- Create the game mode when we activate
function Activate()
	GameRules.AddonTemplate = ClashGameMode()
	GameRules.AddonTemplate:InitGameMode()
end